### ISSUE TITLE
Support FluentValidation >= v9.x.x

### ISSUE THREAD

**Issue by mvdenk** [benmccallum/fairybread#15]
Hi guys, 

Starting with FluentValidation >= 9.x.x the IValidator.Validate(object model) overload has been [removed](https://docs.fluentvalidation.net/en/latest/upgrading-to-9.html#removal-of-non-generic-validate-overload), which is used in this library (InputValidationMiddleware). Suggested change is using a ValidationContext like below, which is also supported in FluentValidation v8.x.x.

```
var context = new ValidationContext<object>(model);
var result = validator.Validate(context);
```

I will create a PR later this week.

**Comment by benmccallum** [comment]
Thanks heaps @mvdenk! I've merged this and bumped the version. Should roll out to nuget as preview.9 shortly.
