### ISSUE TITLE
HC 11 usage

### ISSUE THREAD

**Issue by sergeyshaykhullin** [benmccallum/fairybread#23]
HC changed IServiceCollection api, how can i setup FB for HC 11?
Any doc/api updates?

**Comment by sergeyshaykhullin** [comment]
I found the way

```cs
services.AddGraphQLServer()
  .ConfigureSchema(builder => builder.UseFairyBread())
  .AddErrorFilter<DefaultValidationErrorFilter>()
```

**Comment by benmccallum** [comment]
As mentioned over on the other issue I've added support for HC v11 in v2.0.0 preview 1. Let me know how it goes for you!

If you look in `InputValidationMiddlewareTests` in `GetRequestExecutorAsync` you'll see how to use it with their new api, and FairyBread has a new api too to make things a bit simpler :)
