### ISSUE TITLE
Adding max length to schema

### ISSUE THREAD

**Issue by 206mph** [benmccallum/fairybread#26]
It would be nice if the FluentValidation and/or data annotations could be parsed and output in the schema as directives to document maximum string length, string pattern requirements, and other FluentValidation/data annotation rules. 

In a perfect world, this could extent FluentValidation and/or data annotations to allow for custom descriptions that could be pulled from resource files to support i18n.

**Comment by benmccallum** [comment]
Consolidating this issue and a few others under #39
