### ISSUE TITLE
Client Validation Attributes

### ISSUE THREAD

**Issue by jmercha** [benmccallum/fairybread#29]
ASP.NET MVC has the ability to provide [Client-side Model Validation](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.modelbinding.validation.iclientmodelvalidator?view=aspnetcore-5.0) to the browser as `data-val-*` attributes for usage with [jQuery Validation](https://jqueryvalidation.org/).

It would be fantastic if FairyBread could provide something similar for applications using a SPA stack (GraphQL + React etc.) by exposing the client-side validation attributes from ASP.NET MVC as a [Yup Schema](https://github.com/jquense/yup) for usage with [Formik](https://formik.org/docs/guides/validation#validationschema) and other form libraries.

**Comment by benmccallum** [comment]
Yep, great suggestion, this is definitely something we wanna add here as a new feature. What you've suggested is along the lines of what @maraisr (FED on our team) and I were thinking I believe. 

I'm a bit strapped for time at the moment, but we could start designing it for now. 

One thing that this library currently doesn't do though is support the asp.net mvc / ComponentModel attributes. And to be honest, I'm not sure if we should. FluentValidation support was really the goal of this library. With the attributes, it becomes complicated to fire the validation (no such thing as Model.IsValid or whatever it is in an MVC action), and it didn't look 100% easy to abstract out that validation firing last time I looked. What might be easier is a shim between the attributes and FluentValidator, something I thought would've been done previously but I couldn't find anything last look. That way the attributes would be translated into FV world, and its then business as usual here.

**Comment by benmccallum** [comment]
Something like this maybe:
https://github.com/andreykarinskiy/System.ComponentModel.Annotations.Validation.FluentValidation

**Comment by jmercha** [comment]
I think we could invoke the [adapters from FluentValidation.AspNetCore](https://github.com/FluentValidation/FluentValidation/tree/master/src/FluentValidation.AspNetCore/Adapters) and translate the `data-val-*` attributes into a Yup schema. I'd be happy to try putting together a PR to implement this.

**Comment by benmccallum** [comment]
More than happy to accept a PR! Perhaps we could do it as a separate project and deployed nuget package so folks can opt-in to this addition. Maybe do a quick design in here and we can agree on an approach before you get stuck in.

**Comment by benmccallum** [comment]
Consolidating this issue and a few others under #39
