### ISSUE TITLE
Why isn't IValidationResultHandler.Handle void?

### ISSUE THREAD

**Issue by AradAral** [benmccallum/fairybread#31]
Hi there! First of all, this library is an incredibly useful addition to Hot Chocolate, thanks for building it!

I have 2 questions:

1. The `IValidationResultHandler.Handle` method returns a boolean:
https://github.com/benmccallum/fairybread/blob/a265376da51fe9483694794cd6c3ae3ce779b97c/src/FairyBread/IValidationResultHandler.cs#L17
but that value is apparently not used at all, so why then isn't the method `void` in the first place?!
https://github.com/benmccallum/fairybread/blob/7bfc041e407764859dc443c25c3073d1b326fad9/src/FairyBread/InputValidationMiddleware.cs#L53

2. I'm also intending to customize the GraphQL response for validation errors, I've registered a service for `IValidationResultHandler`, as explained in the [customization](https://github.com/benmccallum/fairybread#customization) section of the README.
Here's my implementation of the `Handle` method:
```csharp
public class CustomValidationResultHandler : IValidationResultHandler
{
    public bool Handle(IMiddlewareContext context, ValidationResult result)
    {
        if (!result.IsValid)
        {
            List<Error> graphQlErrors =
                result.Errors
                .Select(e =>
                    new Error(message: e.ErrorMessage,
                                path: context.Path,
                                locations: new[] {
                                    new Location(context.FieldSelection.Location.Line, context.FieldSelection.Location.Column)
                                },
                                extensions: new Dictionary<string, object>
                                {
                                    ["code"] = "INVALID_INPUT",
                                    ["invalidField"] = ToCamelCase(e.PropertyName),
                                }))
                .ToList();

            throw new GraphQLException(graphQlErrors);
        }
        return false;
    }

    static string ToCamelCase(string str) => char.ToLower(str[0]) + str[1..];
}
```

Basically what this does, and what I wanted, is to generate a response like this: (where every validation error becomes an error object in GraphQL's `errors` array)
```json
{
  "errors": [
    {
      "message": "The firstname shouldn't contain numbers.",
      "locations": [
        {
          "line": 17,
          "column": 3
        }
      ],
      "path": [
        "register"
      ],
      "extensions": {
        "code": "INVALID_INPUT",
        "invalidField": "firstName"
      }
    },
    {
      "message": "The email is not valid.",
      "locations": [
        {
          "line": 17,
          "column": 3
        }
      ],
      "path": [
        "register"
      ],
      "extensions": {
        "code": "INVALID_INPUT",
        "invalidField": "email"
      }
    }
  ]
}
```

Now, there is 1 thing bothering me about this:
As you can see, I'm throwing a `GraphQLException` in the `Handle` method, I also took a look at `InputValidationMiddleware`, and I noticed that the different validation results for different arguments are being passed to the `Handle` method in a loop, but if my `Handle` method throws an exception for the first validation result, then the loop will stop and so the other validation results for other arguments will not be handled, and consequently, their validation errors, if they have any, will not be included in the final result. So, in other words, effectively only the validation error(s) of the first argument will be included in the response.

To avoid stopping that loop, I tried calling `context.ReportError()` instead of throwing an exception in the `Handle` method, but the problem with that is that Fairy Bread itself throws an exception here, after it calls the `Handle` method:
https://github.com/benmccallum/fairybread/blob/7bfc041e407764859dc443c25c3073d1b326fad9/src/FairyBread/InputValidationMiddleware.cs#L77

which means it gets appended to the final GraphQL response as another object in the `errors` array. But that's obviously not what I want. I wanted to do the job of handling validation errors myself. How can I work around this situation? Why does Fairy Bread itself throw an exception, while it promises that it would leave the job of handling the validation errors to the user, if the user decides to do it?

To solve this, can't the `Handle` method instead return an `IEnumerable<HotChocolate.Error>`, which `InputValidationMiddleware` stores, then when it gets out of the loop it throws those errors, or perhaps something like that. Isn't that a viable solution?
Tell me if I'm missing something.
Thanks in advance.

**Comment by AradAral** [comment]
Anybody home?! :)

**Comment by benmccallum** [comment]
Sorry @AradAral! I haven't been checking GitHub lately. I'll try take a look this week/weekend

**Comment by benmccallum** [comment]
I forgot to get rid of `IValidationResultHandler` and its default implementation when I upgraded to HCv11. That was my plan as I was no longer using it.

I'll need to rethink this, possible I bring back the result handler and the default implementation does a `ReportError`. Then the middleware sets the `context.Result` to `null` to abort execution. I just need to think about how that affects our mediatr pipeline which throws the same exception to be handled by the same error handler.

**Comment by benmccallum** [comment]
Hmm, the more I think about it the more I think we need to get rid of the exception entirely, and introduce an error reporter concept that accepts an array of validation results and it can then report errors as it likes. Rather than an error handler which is painful when consumers have their own.

So I'd:
* get rid of the result handler,
* outside the loop, pass the failed validation results to an error builder
* have a default error reporter that does it the way its currently done
* potentially have another reporter that reports an error for each validation error (for AradAral's needs).

**Comment by AradAral** [comment]
@benmccallum Thanks for your response!
> ...and introduce an error reporter concept that accepts an array of validation results and it can then report errors as it likes. 

I think that's a good idea. It's pretty neat. Although I'm not quite sure I understand your last bullet point:
> potentially have another reporter that reports an error for each validation error (for AradAral's needs).

Do you mean a built-in reporter that does it that way alongside the default one that does what Fairy Bread currently does?

Even if that kind of reporter doesn't exist built-in, unless I'm missing something, you could obviously register your custom implementation of the error reporter, which as you mentioned, could form the errors in any style it wants, including having each validation error correspond to an error object in GraphQL's `errors` array (my need), isn't that right?

**Comment by benmccallum** [comment]
Hi @AradAral , I've just pushed a `4.0.0-preview.1` with my idea. Basically all the validation results for all the fields are collected up (without bailing out early), and those are handed to an `IValidationErrorsHandler` to, well, handle. The default implementation now reports an error for each failure for each field. 

The `IValidationResultHandler` has been dropped. I decided it was useless.

Can you give this a go and see if it suits your needs?

If you wanted to slightly change the error reporting, you can just inject your own implementation of `IValidationResultHandler`, even one that inherits the default one and just overrides the `BuildError` method if you wanted to just just one thing for instance. 

I currently have that method returning an IError, but I might change it in preview 2 to return the error builder and do the final `Build` when it reports the error. Avoid instantiating something until it's really ready.

**Comment by benmccallum** [comment]
PS. I haven't done a breaking changes doc yet, but also the IErrorFilter is now gone, so you don't need to register that with the server, which is much nicer.

**Comment by benmccallum** [comment]
Sorry, my code didn't push so it didn't release but it's on nuget now. Cheers

**Comment by AradAral** [comment]
@benmccallum Hi, sorry for the late response.
I checked out the new preview and it's great, the structure makes a lot more sense now. Thank you!
But one thing has been confusing to me. Here:
https://github.com/benmccallum/fairybread/blob/c75ea59771162dbc293a9f6bab16bf242f2cbd72/src/FairyBread/InputValidationMiddleware.cs#L73-L79

Here you're always calling the next middleware component, which means the resolver will be executed even if there are validation errors. Is that intentional?! Shouldn't it instead be:
```csharp
if (invalidResults.Any())
{
    _validationErrorsHandler.Handle(context, invalidResults);
    context.Result = null;
}
else
    await _next(context)
```

Of course I can work around this by throwing a `GraphQLException` in my custom Handle() method, but shouldn't Fairy Bread short-circuit the pipeline if there are any validation errors?

**Comment by benmccallum** [comment]
Yep, I probably should've left a comment there :P I believe by setting `context.Result` to null, the resolver middleware will stop trying to 'resolve' a value for the field. At least that's my understanding; but I'll double check that my unit tests prove that this weekend.

Maybe @michaelstaib or @PascalSenn can confirm 100%. I know I've seen some other middlewares use an else and not call `next`, but I'm not sure what's best. Short-circuiting entirely seems valid, but also potentially letting future middleware still get called could be valid?

**Comment by AradAral** [comment]
@benmccallum 
> I believe by setting context.Result to null, the resolver middleware will stop trying to 'resolve' a value for the field. At least that's my understanding;

I don't think that happens, as long as you're calling the next middleware component, the pipeline execution continues, and you potentially hit the actual resolver, provided that the other middleware components don't short-circuit.

> but also potentially letting future middleware still get called could be valid?

Can you give examples of when that would be desirable?
Even if there are examples, I'm sure 95% of the time you just want to short-circuit the pipeline, or at least that should be the default behavior.

**Comment by benmccallum** [comment]
Thinking about tracing maybe. Would be interested to see whether it would run in time.

**Comment by AradAral** [comment]
> Thinking about tracing maybe. Would be interested to see whether it would run in time.

Sorry is that an example of wanting the pipeline execution to continue? Not sure what you mean there.

**Comment by AradAral** [comment]
Still, the default behavior should be short-circuiting the pipeline if there are any validation errors.
Perhaps a new option could be added in the future to change that for these special cases where you want the pipeline execution to continue.
Don't you agree?

**Comment by benmccallum** [comment]
> I don't think that happens, as long as you're calling the next middleware component the pipeline execution continues, and you potentially ultimately hit the resolver, provided that the other middleware components don't short-circuit the pipeline before that of course. But I don't think it has anything to do with setting context.Result; after setting context.Result you would always have to separately decide if you want the execution of the pipeline to continue or not.
Let me know if I misunderstood what you meant.

Looking at the test results, it's clear that the field's value isn't resolved, and I've confirmed that tracing still comes through so it must wrap the field middleware pipeline.

So I am struggling to find reasons, and it's prob easier to just explicitly not call `next`...

**Comment by AradAral** [comment]
> Looking at the test results, it's clear that the field's value isn't resolved, even though next is called.

The resolver IS called, would you want me to create a repro repository and you can have a look at it?

**Comment by benmccallum** [comment]
All good, will write one now and see

**Comment by benmccallum** [comment]
Just added one and I'm still not seeing it be called. 

I guess it could be risky to assume that setting a Result will continue in future to not run the field's resolver... My unit test/s would fail, but I'm not exactly running them every new HC release... so I'm definitely leaning towards not calling `next`.

**Comment by AradAral** [comment]
I'll publish the repro in just a few minutes...

**Comment by benmccallum** [comment]
Sorry, scratch that, it does get called! I was playing around with the `else` there and was running the test with `else` hahaha. Releasing rc.1.

**Comment by benmccallum** [comment]
FYI, I made that one change to the `DefaultValidationErrorsHandler`. `IError BuildError` is now `IErrorBuilder CreateErrorBuilder` and the `.Build()` gets called by the caller. That way if someone does override it they can use .SetMessage() rather than .WithMessage() and not be throwing out the existing immutable IError and we only create one right when needed.

4.0.0-rc.1 should be up in 5mins or so.

**Comment by AradAral** [comment]
Ah, cool! :P
Thank you.

**Comment by AradAral** [comment]
All is well. I think we can now close this issue.
Thanks so much for your efforts! 👍

**Comment by benmccallum** [comment]
No worries, will push 4.0.0 now. Cheers for the issue and feedback.
