### ISSUE TITLE
Incompatibility with Hot Chocolate v11.0.8

### ISSUE THREAD

**Issue by AradAral** [benmccallum/fairybread#34]
I updated Hot Chocolate to version the newest version today "11.0.8", and Fairy Bread seems to have problems with this version.
I have the following 3 packages installed, alongside Fairy Bread 3.0.0 of course:
- HotChocolate.AspNetCore (v11.0.8)
- HotChocolate.AspNetCore.Authorization (v11.0.8)
- HotChocolate.Data (v11.0.8)

The exception that's thrown:
> Method not found: 'System.Collections.Generic.IReadOnlyDictionary`2<System.String,System.Object> HotChocolate.Types.IField.get_ContextData()'.

Stacktrace:
> at FairyBread.DefaultFairyBreadOptions.DefaultImplementations.ShouldValidateBasedOnValidateDescriptor(IMiddlewareContext context, IInputField argument)\r\n   at FairyBread.DefaultFairyBreadOptions.DefaultImplementations.ShouldValidate(IMiddlewareContext context, IInputField argument)\r\n   at FairyBread.InputValidationMiddleware.InvokeAsync(IMiddlewareContext context)\r\n   at HotChocolate.Utilities.MiddlewareCompiler`1.ExpressionHelper.AwaitTaskHelper(Task task)\r\n   at HotChocolate.Execution.Processing.ResolverTask.ExecuteResolverPipelineAsync(CancellationToken cancellationToken)\r\n   at HotChocolate.Execution.Processing.ResolverTask.TryExecuteAsync(CancellationToken cancellationToken)

![image](https://user-images.githubusercontent.com/26527405/105366273-63e53880-5c14-11eb-9082-29e3e443d7cc.png)

I had to go back to v11.0.0 temporarily, I'd appreciate it if this is addressed pretty soon. Thanks!

**Comment by benmccallum** [comment]
Hey @AradAral , thanks for reporting. I'm having a hard time reproducing this. It would seem from the stack trace that it's failing when it tries to do `argument.ContextData`, but after bumping to 11.0.8, that property still exists and all tests still pass. 

Are you able to produce a small test that reproduces it? Thanks!

**Comment by benmccallum** [comment]
Tried 11.0.9-preview.3 too, seems ok.

**Comment by benmccallum** [comment]
Tried 11.1.0-preview.8 too, seems ok.

**Comment by AradAral** [comment]
I can't seem to reproduce this again either! 😄
I have no idea what was going on at the time. Seems to be working well right now.
Thank you.

**Comment by JardarM** [comment]
I get this error when I try to run a QUERY and not a mutation. When running a mutation it seems to work fine.
Using Hot Chocholate 11.0.9 and latest Fairy Bread 4.1.0.

Query:
```
{
  controller(id:"iotEdge-A"){
    chargePoints{clusterId}
  }
}
```

Response
```
[
  {
    "message": "System.MissingMethodException: Method not found: 'System.Collections.Generic.IReadOnlyDictionary`2<System.String,System.Object> HotChocolate.Types.IField.get_ContextData()'.\r\n   at FairyBread.DefaultFairyBreadOptions.DefaultImplementations.ShouldValidateBasedOnValidateDescriptor(IMiddlewareContext context, IInputField argument)\r\n   at FairyBread.DefaultFairyBreadOptions.DefaultImplementations.ShouldValidate(IMiddlewareContext context, IInputField argument)\r\n   at FairyBread.InputValidationMiddleware.InvokeAsync(IMiddlewareContext context)\r\n   at HotChocolate.Utilities.MiddlewareCompiler`1.ExpressionHelper.AwaitTaskHelper(Task task)\r\n   at HotChocolate.Execution.Processing.ResolverTask.ExecuteResolverPipelineAsync(CancellationToken cancellationToken)\r\n   at HotChocolate.Execution.Processing.ResolverTask.TryExecuteAsync(CancellationToken cancellationToken)",
    "locations": [
      {
        "line": 2,
        "column": 3
      }
    ],
    "path": [
      "controller"
    ],
    "extensions": {
      "message": "Method not found: 'System.Collections.Generic.IReadOnlyDictionary`2<System.String,System.Object> HotChocolate.Types.IField.get_ContextData()'.",
      "stackTrace": "   at FairyBread.DefaultFairyBreadOptions.DefaultImplementations.ShouldValidateBasedOnValidateDescriptor(IMiddlewareContext context, IInputField argument)\r\n   at FairyBread.DefaultFairyBreadOptions.DefaultImplementations.ShouldValidate(IMiddlewareContext context, IInputField argument)\r\n   at FairyBread.InputValidationMiddleware.InvokeAsync(IMiddlewareContext context)\r\n   at HotChocolate.Utilities.MiddlewareCompiler`1.ExpressionHelper.AwaitTaskHelper(Task task)\r\n   at HotChocolate.Execution.Processing.ResolverTask.ExecuteResolverPipelineAsync(CancellationToken cancellationToken)\r\n   at HotChocolate.Execution.Processing.ResolverTask.TryExecuteAsync(CancellationToken cancellationToken)"
    }
  }
]
```

**Comment by benmccallum** [comment]
@JardarM let's continue this on #37 , seems a tricky one to figure out.
