### ISSUE TITLE
Using FluentValidation (10.0.0) errors with Method not found 

### ISSUE THREAD

**Issue by d-lundy** [benmccallum/fairybread#41]
**Summary**
When running through FairyBread, validation fails with trying to get the property Errors from the FluentVallidation.Results.ValidationResult.

**Expected behavior**
The mutation will execute and either fail because of validation errors or pass.

**Screenshots**
![image](https://user-images.githubusercontent.com/8311112/114052220-db158a80-985b-11eb-8cc7-07167b092d95.png)

**Steps To Reproduce**
1. Run a mutation with an input that has a registered validator.
2. The following error in the screenshot is returned.

**Versions:**
 - FairyBread: 5.1.0
 - HotChocolate: 11.1.0
 - FluentValidation: 10.0.0

**Comment by benmccallum** [comment]
Thanks for reporting @d-lundy, might be because of this:
https://docs.fluentvalidation.net/en/latest/upgrading-to-10.html#validationresult-errors-type-change

I should be able to fix it today.

**Comment by benmccallum** [comment]
Hi @d-lundy, I've pushed a `6.0.0-rc.1` built against FV v10, can you give that a go and see if it resolves your issue? Then I'll push v6 proper. Cheers!

**Comment by d-lundy** [comment]
The change fixed the issue.  Thank you.

**Comment by benmccallum** [comment]
Fixed in v6.0.0.
