### ISSUE TITLE
Mutation Without Input Bypasses NotEmpty Validation

### ISSUE THREAD

**Issue by JarrydVanHoy** [benmccallum/fairybread#57]
Here is my basic validation:
```
public class AddUsersInputValidator : AbstractValidator<List<AddUserInput>>
{
	public AddUsersInputValidator()
	{
		RuleFor(r => r).NotEmpty().WithMessage("Must provide input");
	}
}
```
**Issue 1**: If I change from List<<T>> to IEnumerable<<T>> or T[], then this validation never seems to fire.

**Issue 2**: If I neglect to add the input as part of my request, then I'll be able to enter my endpoint which appears to bypass my validation.  
The validation appears to work when I pass a mutation as follows:
```
mutation{
  addUser(input: []){
    firstName
  }
}
```
But fails to perform validation with the following mutations:
```
mutation{
  addUser{
    ...
```
or
```
mutation{
  addUser(){
    ...
```
or
```
mutation{
  addUser(input: null){
    ...
```
Is there something wrong with what I'm doing or is there an issue with FluentValidation, FairyBread, or even HotChocolate?

**Versions:**
 - FairyBread: 7.0.0-rc.1
 - HotChocolate: 11.3.1
 - FluentValidation: 10.3.0

**Comment by benmccallum** [comment]
FairyBread doesn't validate an argument that is `null`. It's sort of assumed that if the argument type supports null at the schema level that that is valid.

It seems a bit bizarre to allow the passing of a null here, so I'd first change it to:
`addUsers(input: [AddUserInput!]!)`

That way HotChocolate will actually validate it to the graphql spec and client tooling will show that null isn't allowed.

One scenario where null could be allowed but you sometimes want to validate it isn't null, would be a property within the input type where null is allowed conditionally with `When`, but that'd be based off another property on the input type and the input type would be non-null.

That brings me to how I see this. I think the design of your mutation field is wrong. Keen to see what @mstaib or @pascalsenn think. To me you should always have a single, top-level arg on your mutation field that's non-nullable, e.g. `createBooking(input: CreateBookingInput!)` and then inside that you can have optional properties as needed. Then your input is always guaranteed to be non-nullable and the validator will always be fired.
```
type CreateUsersInput {
  users: [CreateUsersUserInput!]!
}
```

Aside: This is sort of related to an open issue #56 about supporting auto-validation of arrays of T, if there's a validator for T, which I'm thinking about rejecting as it fails into a similar problem. Unique, non-null, top-level input type per mutation name is the way to go.

**Comment by JarrydVanHoy** [comment]
Awesome, thank you @benmccallum .  That lead me to find the attribute to perform this code side: [Non-null Attribute](https://chillicream.com/docs/hotchocolate/defining-a-schema/non-null) .

As for the mutation design, I'm always open to hearing different points of view.  So again, thank you for you speedy response and input.  If the other peeps have input too, I'm all ears.
