### ISSUE TITLE
Where is `UseValidation`?

### ISSUE THREAD

**Issue by AradAral** [benmccallum/fairybread#64]
Hi there.
To enable validation for a query field's argument, previously in v6, Fairy Bread provided an extension method on `IArgumentDescriptor`, called `UseValidation`.
I updated to v8.0.0rc now, that method seems to have been removed and I'm getting an error.
I then downgraded to v7, and I found that it's not there either.
What happened to this functionality?!

**Comment by benmccallum** [comment]
Hi @AradAral , have a read of the release notes for v7. You don't need to call UseValidation on query field args as the default is for the arg to be validated now :) Pushes you down the pit of success.

I'm about to release v7.1 which optimizes the middleware placement even further.

v8 will bring this all together on HCv12.

**Comment by AradAral** [comment]
> have a read of the release notes for v7

Sorry, don't know why that didn't occur to me...

> You don't need to call UseValidation on query field args as the default is for the arg to be validated now :) Pushes you down the pit of success.

Wow, that's some genius-level stuff! :P Impressive!
Thanks, Ben.

**Comment by benmccallum** [comment]
No worries @AradAral , def always a good idea to check the notes on a major bump as I follow semver as much as possible.

Type interceptors are awesome and have opened a lot of doors. I think it's make the explicit configuration easier too :)
