### ISSUE TITLE
Support for HotChocolate.Execution > 12.4.0?

### ISSUE THREAD

**Issue by wondering639** [benmccallum/fairybread#76]
What about support for e.g. [12.6.0](https://www.nuget.org/packages/HotChocolate.Execution/12.6.0) or [12.5.0](https://www.nuget.org/packages/HotChocolate.Execution/12.5.0) ? 

According to https://github.com/benmccallum/fairybread#compatibility only 12.4.0 is supported? Or is only the readme outdated?

**Comment by benmccallum** [comment]
This is a minimum version, so anything above 12.4 is supported, no worries :)
