### ISSUE TITLE
Please provide a NuGet for FairyBread v9

### ISSUE THREAD

**Issue by wondering639** [benmccallum/fairybread#81]
**Describe the bug**
No NuGet for FairyBread v9. I know it is still a release candidate, but it could be marked as such and still be available as NuGet. Without a NuGet package it gets tricky on some cloud build systems that expect dependencies as NuGet. Also adding a NuGet is easier than adding FairyBread and it's dependencies manually :-)

**To Reproduce**
1. Check available NuGet packages

**Expected behavior**
NuGet package for v9 RC

**Screenshots**
-

**Versions:**
 - FairyBread: v9 RC
 - HotChocolate: latest one which requires FairyBread v9 RC
 - FluentValidation: n/a

**Comment by wondering639** [comment]
> What am I missing... https://www.nuget.org/packages/FairyBread/9.0.0-rc.1 ? Is this not working for you?

ah, my fault. I forgot to tick the "Include prerelease" checkbox in the NuGet Explorer
![image](https://user-images.githubusercontent.com/25722498/172877925-d29d9daa-127c-422f-9e05-c4f014a769d9.png)

Thanks for pointing me at this :-)

**Comment by benmccallum** [comment]
I think I forgot to release 9.0.0 a while back after doing an RC, but I just pushed one now anyway and I'll just move the one issue I was going to get in there into a 9.1 milestone.

Thanks @FleloShe for the help too :)
