### ISSUE TITLE
Custom `IValidationErrorsHandler` union types?

### ISSUE THREAD

**Issue by leebenson** [benmccallum/fairybread#90]
Thanks for a great helper lib!

I'd like to build an error handler that returns strongly typed errors rather than the free-for-all that is a top-level `errors` field.

Generally, if I was doing this manually, it'd look something like:

```gql
union SomeResponse = TSuccessType | ValidationErrors
```

I assume I could just attach the strongly typed error to `context.Result`, but I'm curious how to update Hot Chocolate's interpretation of the method return type so that it's refactored as a union of `T | ValidationErrors` rather than just `T`. Do you know if there any good way to do that I'm overlooking?

Thanks in advance for any pointers. I think a helper there would make a good addition to the library.

**Comment by glen-84** [comment]
Might be relevant: https://github.com/ChilliCream/graphql-platform/issues/5549#issuecomment-1378710725.

**Comment by benmccallum** [comment]
Going to close this in favour of #77 which I hope will solve this. I'll start up the discussion over there shortly and we can all review.
