### ISSUE TITLE
Not working with Hot Chocolate 13?!

### ISSUE THREAD

**Issue by aradalvand** [benmccallum/fairybread#91]
I have Fairy Bread version 10.0.0-preview.2 with Hot Chocolate 13.0.5, and Fairy Bread doesn't work at all.

Dead-simple repro: https://github.com/aradalvand/hc-fairybread-test
Steps:
- Start the project linked above
- Run the following mutation:
```graphql
mutation {
    doFoo(input: { text: "ABC" })
}
```
Expected behavior:
It should yield a validation error since `"ABC"` is less than 5 characters.
Actual behavior:
No validation error and the resolver is executed.

Any ideas? Am I doing something wrong?!

**Comment by xamir82** [comment]
Same here.

**Comment by benmccallum** [comment]
Seems like HCv13 shipped with a lot of changes. Looks like potentially the changes in the `TypeInterceptor` (diff signature of the method I was implementing) are what maybe caused the middleware to not register 🤷🏻 

Just got a rc1 out, so please give that a try and let me know.

**Comment by aradalvand** [comment]
Hi @benmccallum!
It seems like it now works in RC1. Thank you!

**Comment by benmccallum** [comment]
No worries. Certainly an interesting situation in that it wouldn't validate but didn't blow up on startup. 

I need like integration tests that run daily that look for the latest HC version and try use it. Right now I'm relying on people on the bleeding edge finding these things, so thanks like always for reporting.

**Comment by benmccallum** [comment]
I'll release V10 in the next few days.

**Comment by aradalvand** [comment]
> Certainly an interesting situation in that it wouldn't validate but didn't blow up on startup.

Exactly, that was weird, it's why I was initially convinced I was making a mistake, scratching my head having no clue why it wasn't working but also not yielding an error or something! :D

> I need like integration tests that run daily that look for the latest HC version and try use it.

Yeah, I think that would be ideal, it'll make things really robust.

> Right now I'm relying on people on the bleeding edge finding these things, so thanks like always for reporting.

No worries!
