### ISSUE TITLE
Not working with Hot Chocolate 14

### ISSUE THREAD

**Issue by mormegill** [benmccallum/fairybread#94]
Hot Chocolate v14.0.0 have [breaking changes in v14](https://github.com/ChilliCream/graphql-platform/releases/tag/14.0.0) for FairyBread v10.0.0,

Created a [fork PR](https://github.com/benmccallum/fairybread/pull/93)

**Comment by benmccallum** [comment]
Thanks @mormegill , can you let me know if 11.0.0-rc.1 works for you and if so I'll publish 11.0.0 tomorrow!

**Comment by mormegill** [comment]
I’ll try to get it tested. However, we might want to use v14.1.0 of HC
asap.

**Comment by benmccallum** [comment]
Thanks :) 

Re: 14.1, any particular reason why? Would it need a new/corresponding FairyBread release?

**Comment by mormegill** [comment]
Nope, I just thought it would match with the latest version but there was
no relevant changes in 14.1 and they are already working with 15.

**Comment by mormegill** [comment]
Build, run and test 11.0.0-rc.1 ok with HC 14.0.0!
